# openspec-shim: resolves to installed plugin version
"""Shim for config_loader.py — generated by migrate_to_plugin.py (issue #33).

Project-own hooks import this module (e.g. ``import config_loader`` or
``from config_loader import X``). Instead of keeping a stale local copy, this
shim loads the real module from the installed agent-os-openspec plugin and
re-exports all of its public attributes, so both import styles keep working.
"""
import importlib.util
import json
import os


def _resolve_plugin_module():
    registry = os.path.expanduser("~/.claude/plugins/installed_plugins.json")
    install_path = ""
    try:
        with open(registry) as _fh:
            _data = json.load(_fh)
        for _key, _entries in _data.get("plugins", {}).items():
            if not _key.startswith("agent-os-openspec@"):
                continue
            _entry = next(
                (_e for _e in _entries if _e.get("scope") == "user"),
                _entries[0],
            )
            install_path = _entry.get("installPath", "")
            break
    except Exception:
        install_path = ""

    if install_path:
        _module_path = os.path.join(
            install_path, "core", "hooks", "config_loader.py"
        )
        if os.path.isfile(_module_path):
            _spec = importlib.util.spec_from_file_location(
                "config_loader", _module_path
            )
            _module = importlib.util.module_from_spec(_spec)
            _spec.loader.exec_module(_module)
            return _module

    raise ImportError(
        "agent-os-openspec plugin not installed "
        "— install it or restore local hooks"
    )


globals().update(
    {
        _name: _value
        for _name, _value in vars(_resolve_plugin_module()).items()
        if not _name.startswith("__")
    }
)
